import type { ChalklinePlugin } from "./types";

export const chalklinePlugins: ChalklinePlugin[] = [
  {
    id: "canvas",
    name: "Canvas",
    shortName: "Canvas",
    category: "LMS",
    description: "Send tomorrow's lesson, assignments, rubrics, and teacher-approved materials to a Canvas course.",
    status: "district_setup",
    color: "#c43a2f",
    mark: "C",
    capabilities: ["course.read", "assignment.write", "evidence.export"],
    setup: "District Canvas URL and an administrator-approved developer key or LTI 1.3 registration.",
    fallback: "Download a Canvas-ready assignment package and teacher evidence CSV.",
    regionNote: "Publicly listed by Dalton Public Schools for students and staff.",
  },
  {
    id: "infinite-campus",
    name: "Infinite Campus",
    shortName: "Campus",
    category: "SIS",
    description: "Bring in sections and export teacher-approved scores or evidence summaries without replacing the official gradebook.",
    status: "file_handoff",
    color: "#24785f",
    mark: "IC",
    capabilities: ["roster.read", "gradebook.write", "evidence.export"],
    setup: "Works now with roster and gradebook CSV files; direct API access requires district approval.",
    fallback: "Roster import and gradebook export use explicit column mapping with a preview before download.",
    regionNote: "Publicly used by Rome City, Dalton, Whitfield County, and Walker County schools.",
  },
  {
    id: "clever",
    name: "Clever",
    shortName: "Clever",
    category: "Roster & SSO",
    description: "Launch Chalkline from a district portal and keep course rosters aligned through an approved district connection.",
    status: "district_setup",
    color: "#2f6dd5",
    mark: "C",
    capabilities: ["roster.read", "course.read", "sso.launch"],
    setup: "A district Clever application approval and scoped roster permissions.",
    fallback: "Use a OneRoster CSV export until district provisioning is complete.",
    regionNote: "Publicly listed by Dalton and Walker County schools.",
  },
  {
    id: "classlink",
    name: "ClassLink",
    shortName: "ClassLink",
    category: "Roster & SSO",
    description: "Support single sign-on and OneRoster-based class synchronization for participating districts.",
    status: "district_setup",
    color: "#ef8b2c",
    mark: "CL",
    capabilities: ["roster.read", "course.read", "sso.launch"],
    setup: "A district ClassLink application assignment and OneRoster access.",
    fallback: "Import a district-exported OneRoster CSV bundle locally.",
    regionNote: "Whitfield County's Infinite Campus portal publicly exposes ClassLink SSO.",
  },
  {
    id: "oneroster-csv",
    name: "OneRoster / CSV",
    shortName: "CSV",
    category: "Portable",
    description: "Move rosters, evidence, and gradebook-ready records without waiting for a vendor API agreement.",
    status: "ready",
    color: "#655b4f",
    mark: "CSV",
    capabilities: ["roster.read", "evidence.export", "gradebook.write"],
    setup: "No account required. Files stay on this device in the current prototype.",
    fallback: "Not needed — this is the portable handoff path.",
    regionNote: "Designed as the common denominator across Northwest Georgia district stacks.",
  },
];

export function getPlugin(id: string) {
  return chalklinePlugins.find((plugin) => plugin.id === id);
}

